### ISSUE TITLE
Make and send posts to a central feed

### ISSUE THREAD

**Issue by bradlet** [bradlet/broadboards#2]
## User Story
As a user, I would like to be able to make posts to a main feed.

## Description
Must have some container to hold posts that will be displayed on the website. Need some way to send posts to this container across a network connection. Need to get that post info from a "create post" section in the website UI.

## Acceptance Criteria
- Info successfully pulled from UI section, and sent over network connection to the feed

**Comment by SulimanCS** [comment]
This is a done-done based on our current project state
