### ISSUE TITLE
Posts stored in a database

### ISSUE THREAD

**Issue by bradlet** [bradlet/broadboards#5]
## User Story
As a user, I would like my posts to be stored in a database and persist for some time.

## Description
The posts should also be held in a database so that they can persist. Maybe the "container" mentioned in other sections is the database, or that container updates a database, tbd.

## Acceptance Criteria
- Posts are persistant in some way.

**Comment by SulimanCS** [comment]
Posts are now stored successfully, thus making this issue 'done'
